/*
 * ultrasonic.h
 *
 *  Created on: Oct 25, 2021
 *      Author: as
 */

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "std_types.h"

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/
/* Ultrasonic HW Ports and Pins Ids */
#define TRIGGER_PORT_ID        PORTB_ID
#define TRIGGER_PIN_ID         PIN5_ID

#define ECHO_PORT_ID           PORTD_ID
#define ECHO_PIN_ID            PIN6_ID


/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/*
 * Description :
 * Initialize the ultrasonic:
 * 1. Initialize the ICU driver.
 * 2. Setup the ICU callback function.
 * 3. Setup the direction for the trigger pin as output pin through the GPIO driver.
 */

void Ultrasonic_init(void);
/*
 * Description :
 * Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void);
/*
 * Description :
 * 1. Send the trigger pulse by using Ultrasonic_Trigger function.
 * 2. Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void);
/*
 * Description :
 * 1. This is the call back function called by the ICU driver.
 * 2. This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);

#endif /* ULTRASONIC_H_ */
