/*
 * ultrasonic.c
 *
 *  Created on: Oct 25, 2021
 *      Author: as
 */
#include <util/delay.h>
#include "common_macros.h"
#include "ultrasonic.h"
#include "gpio.h"
#include"icu.h"

uint8 g_edgeCount = 0;
uint16 g_timeHigh = 0;
uint16 distance=0;
/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/

/*
 * Description :
 * Initialize the ultrasonic:
 * 1. Initialize the ICU driver.
 * 2. Setup the ICU callback function.
 * 3. Setup the direction for the trigger pin as output pin through the GPIO driver.
 */

void Ultrasonic_init(void){
	Icu_ConfigType Icu_Config={F_CPU_8,RISING};
	Icu_init(&Icu_Config);
	Icu_setCallBack(Ultrasonic_edgeProcessing);
	GPIO_setupPinDirection(TRIGGER_PORT_ID,TRIGGER_PIN_ID,PIN_OUTPUT);
}
/*
 * Description :
 * Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void){
	GPIO_writePin(TRIGGER_PORT_ID,TRIGGER_PIN_ID,LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(TRIGGER_PORT_ID,TRIGGER_PIN_ID,LOGIC_LOW);
}
/*
 * Description :
 * 1. Send the trigger pulse by using Ultrasonic_Trigger function.
 * 2. Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void){
	Ultrasonic_Trigger();
    distance=0.017*g_timeHigh;
    return distance;
}
/*
 * Description :
 * 1. This is the call back function called by the ICU driver.
 * 2. This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void){
	g_edgeCount++;
		if(g_edgeCount == 1)
		{
			/*
			 * Clear the timer counter register to start measurements from the
			 * first detected rising edge
			 */
			Icu_clearTimerValue();
			/* Detect falling edge */
			Icu_setEdgeDetectionType(FALLING);
		}
		else if(g_edgeCount == 2)
		{
			/* Store the High time value */
			g_timeHigh = Icu_getInputCaptureValue();
			/* Clear the timer counter register to start measurements again */
			Icu_clearTimerValue();
			/* Detect rising edge */
			Icu_setEdgeDetectionType(RISING);
		}
}
